//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANMOI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bai_viet
    {
       
        public int BaiVietID { get; set; }
        [Required(ErrorMessage = "Tiêu đề là bắt buộc.")]
        [StringLength(200, ErrorMessage = "Tiêu đề không được vượt quá 200 ký tự.")]
        public string TieuDe { get; set; }
        [Required(ErrorMessage = "Nội dung là bắt buộc.")]
        public string NoiDung { get; set; }
        public Nullable<int> DanhMucID { get; set; }
       
        public string Hinh_Anh { get; set; }

        public Nullable<System.DateTime> Thoi_Gian_Tao { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Danh_Muc Danh_Muc { get; set; }
        public virtual User User { get; set; }
    }
}
